issuer: http://localhost:5556
authorization_endpoint: http://dex:5556/auth
token_endpoint: http://dex:5556/token
jwks_uri: http://dex:5556/keys
userinfo_endpoint: http://dex:5556/userinfo
device_authorization_endpoint: http://localhost:5556/device/code

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: taskify-client
    redirectURIs:
      - http://localhost:8000/auth
      - http://localhost:8000/authorize
    name: Taskify Application
    secret: your-secret-key-here-change-this

enablePasswordDB: true

staticPasswords:
  - email: admin@hw3.com
    hash: "$2b$10$8NoCpIs/Z6v0s/pU9YxYIO10uWyhIVOS2kmNac9AD0HsqRhP5dUie"
    username: admin
    userID: "123"
  - email: moderator@hw3.com
    hash: "$2b$12$2aaoZyVjMWvoCq.DmCUECOGoW0oaBCyzSluUm3BpLrP26sVT71PSC"
    username: moderator
    userID: "456"
  - email: user@hw3.com
    hash: "$2b$12$321HomfT164U9f5l.xQaYuHThGCss8PRPNy8t./tq8Frgr6UYeEka"
    username: user
    userID: "789"

oauth2:
  skipApprovalScreen: true
